name: build-docker-and-publish

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VERSION_NUMBER: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            semanticexperts/node-chromium
          tags: |
            type=raw,value=${{env.VERSION_NUMBER}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DOCKER_BUILD_NODE_VERSION=${{env.VERSION_NUMBER}}
